apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
      - name: accounts
        image: IMAGE_NAME_HERE
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_HOST
          value: postgresql
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: database-name
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: database-password
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: database-user
